version: '3'
services:
  rabbitmq:
    hostname: "rabbit"
    image: "rabbitmq:3.9-management"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5552:5552"
    volumes:
      - "../../volumes/rabbitmq/mnesia:/var/lib/rabbitmq/mnesia/"
      - "../../volumes/rabbitmq/log:/var/log/rabbitmq"
      - "./config:/etc/rabbitmq"
    networks:
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge