version: '3'
services:
  postgresql:
    image: "postgres:latest"
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - pg.env
    volumes:
      - "../../volumes/postgres/data:/var/lib/postgresql/data/"
    networks:
      - postgresql

networks:
  postgresql:
    driver: bridge