services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "./data:/cockroach/cockroach-data"
    networks:
      - cockroachnet

networks:
  cockroachnet:
    driver: bridge